server:
  port: 8050
spring:
  application:
    name: hdcommon-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gift1985/config-repo
          username: gift1985@163.com
          password: 19850209sunwei06
          clone-on-start: true
logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.boot: INFO
encrypt:
  key: holdtime